"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import KnowledgeVaultShell from "../KnowledgeVaultShell";
import LearningObjectRenderer from "../LearningObjectRenderer";

type Obj = Record<string, any>;
const modeTabs=["Quick Scan","Learn","Quiz","Timeline","Saved"];
function routeFor(label:string){return `/knowledge-vault/${label.toLowerCase().replace(" ","-")}`;}
function clientKey(){const k="capital-forge-kv-client-v1";let v=localStorage.getItem(k);if(!v){v=`cfkv-${crypto.randomUUID()}`;localStorage.setItem(k,v);}return v;}
function titleCase(v:string){return decodeURIComponent(v||"").replaceAll("-"," ").replace(/\b\w/g,m=>m.toUpperCase());}

export default function KnowledgeVaultRoutePage(){
  const params=useParams<{slug:string[]}>();
  const slug=Array.isArray(params?.slug)?params.slug:[];
  const section=slug[0]||"learn";
  const detail=slug[1]||"";
  const [search,setSearch]=useState("");
  return <KnowledgeVaultShell search={search} onSearch={setSearch}><main className="kv-mode-workspace"><div className="kv-mode-head"><div><div className="kv-crumb">Knowledge Vault <span>›</span> {titleCase(section)}</div><h1>{section==="object"?"Learning Object":section==="quick-scan"?"Quick Scan":section==="universe"?titleCase(detail):section==="category"?titleCase(detail):titleCase(section)}</h1><p>{section==="quick-scan"?"Fast recall with spaced repetition and confidence rating.":section==="timeline"?"Financial history from dated, source-grounded objects.":section==="saved"?"Bookmarks, review-later items, mastered objects and recent history.":"Browse, understand and connect finance knowledge."}</p></div><div className="kv-mode-tabs">{modeTabs.map(x=><button key={x} className={section===x.toLowerCase().replace(" ","-")?"active":""} onClick={()=>window.location.assign(routeFor(x))}>{x}</button>)}</div></div><div className="kv-mode-panel">{section==="object"?<ObjectView id={detail}/>:section==="quick-scan"?<QuickScan/>:section==="quiz"?<Quiz/>:section==="timeline"?<Timeline search={search}/>:section==="saved"?<Saved/>:section==="universe"?<Universe slug={detail}/>:section==="progress"?<ProgressRedirect/>:<Learn category={section==="category"?detail:""} search={search}/>}</div></main></KnowledgeVaultShell>;
}

function Empty({text="No canonical Knowledge Vault objects are available yet."}:{text?:string}){return <div className="kv-mode-card kv-empty"><b>{text}</b><p>The interface is data-driven and will populate immediately after the canonical CF3 JSONL import.</p></div>}

function ObjectView({id}:{id:string}){
  const [object,setObject]=useState<Obj|null>(null);const [sources,setSources]=useState<any[]>([]);const [busy,setBusy]=useState(true);const [bookmarked,setBookmarked]=useState(false);const [reviewLater,setReviewLater]=useState(false);
  useEffect(()=>{(async()=>{setBusy(true);const res=await fetch(`/api/knowledge-vault?action=object&id=${encodeURIComponent(id)}`,{cache:"no-store"});const data=await res.json();if(data.ok){setObject(data.object);setSources(data.sources||[]);await fetch("/api/knowledge-vault",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"seen",clientKey:clientKey(),objectId:data.object.id})});}setBusy(false);})();},[id]);
  async function toggle(action:"bookmark"|"reviewLater",value:boolean){if(!object)return;await fetch("/api/knowledge-vault",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,clientKey:clientKey(),objectId:object.id,value})});if(action==="bookmark")setBookmarked(value);else setReviewLater(value);}
  if(busy)return <div className="kv-mode-card">Loading object…</div>;if(!object)return <Empty/>;
  return <><div className="kv-filter-row"><button onClick={()=>history.back()}>← Back</button><button onClick={()=>toggle("bookmark",!bookmarked)}>{bookmarked?"★ Bookmarked":"☆ Bookmark"}</button><button onClick={()=>toggle("reviewLater",!reviewLater)}>{reviewLater?"✓ Review Later":"↻ Review Later"}</button><button onClick={()=>window.location.assign(`/knowledge-vault/quick-scan?object=${object.id}`)}>Quick Scan This →</button></div><LearningObjectRenderer object={object} sources={sources}/><Related object={object}/></>;
}

function Related({object}:{object:Obj}){const [rows,setRows]=useState<Obj[]>([]);useEffect(()=>{if(!object?.category_slug)return;(async()=>{const res=await fetch(`/api/knowledge-vault?action=list&category=${encodeURIComponent(object.category_slug)}&limit=4`);const data=await res.json();if(data.ok)setRows((data.objects||[]).filter((x:Obj)=>x.id!==object.id).slice(0,3));})();},[object]);if(!rows.length)return null;return <section className="kv-mode-card" style={{marginTop:12}}><h3>Continue the chain</h3><div className="kv-browser-grid">{rows.map(x=><button key={x.id} className="kv-browser-card" onClick={()=>window.location.assign(`/knowledge-vault/object/${x.id}`)}><small>{x.category}</small><h3>{x.title}</h3><p>{x.topic||x.content_type}</p></button>)}</div></section>}

function Learn({category,search}:{category:string;search:string}){
  const [rows,setRows]=useState<Obj[]>([]);const [universe,setUniverse]=useState("");const [difficulty,setDifficulty]=useState("");const [busy,setBusy]=useState(true);
  useEffect(()=>{const timer=setTimeout(async()=>{setBusy(true);const p=new URLSearchParams({action:"list",limit:"50"});if(category)p.set("category",category);if(universe)p.set("universe",universe);if(search)p.set("q",search);const res=await fetch(`/api/knowledge-vault?${p}`);const data=await res.json();let list=data.ok?(data.objects||[]):[];if(difficulty)list=list.filter((x:Obj)=>String(x.difficulty||5)===difficulty);setRows(list);setBusy(false);},180);return()=>clearTimeout(timer);},[category,universe,difficulty,search]);
  return <section className="kv-mode-card"><div className="kv-filter-row"><select value={universe} onChange={e=>setUniverse(e.target.value)}><option value="">All Universes</option><option>Technicals</option><option>Market History</option><option>Legendary Trades & Deals</option><option>Crises & Events</option><option>Finance Facts</option></select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All Difficulty</option>{[1,2,3,4,5,6,7,8,9,10].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>window.location.assign("/knowledge-vault/quick-scan")}>Start Quick Scan →</button></div>{busy?<p>Loading…</p>:rows.length?<div className="kv-browser-grid">{rows.map(x=><button className="kv-browser-card" key={x.id} onClick={()=>window.location.assign(`/knowledge-vault/object/${x.id}`)}><small>{x.universe} · D{x.difficulty}</small><h3>{x.title}</h3><p>{x.category} · {x.topic||x.content_type}</p></button>)}</div>:<Empty/>}</section>;
}

function Universe({slug}:{slug:string}){
  const universeMap:Record<string,string>={"technicals":"Technicals","market-history":"Market History","legendary-trades-deals":"Legendary Trades & Deals","crises-events":"Crises & Events","finance-facts":"Finance Facts"};const universe=universeMap[slug]||titleCase(slug);const [cats,setCats]=useState<any[]>([]);
  useEffect(()=>{(async()=>{const res=await fetch(`/api/knowledge-vault?action=categories&universe=${encodeURIComponent(universe)}`);const data=await res.json();if(data.ok)setCats(data.categories||[]);})();},[universe]);
  if(!cats.length)return <Empty text={`${universe} is ready for its canonical category import.`}/>;return <section className="kv-mode-card"><div className="kv-browser-grid">{cats.map(c=><button className="kv-browser-card" key={c.slug} onClick={()=>window.location.assign(`/knowledge-vault/category/${c.slug}`)}><small>{universe}</small><h3>{c.name}</h3><p>0 / {c.count||120} reviewed · 0% mastery · 0% accuracy</p><b>Continue →</b></button>)}</div></section>;
}

function QuickScan(){
  const [rows,setRows]=useState<Obj[]>([]);const [index,setIndex]=useState(0);const [revealed,setRevealed]=useState(false);const [session,setSession]=useState<any>(null);const [busy,setBusy]=useState(true);
  async function load(){setBusy(true);const qs=new URLSearchParams(window.location.search);const count=Math.min(50,Math.max(1,Number(qs.get("count")||10)));const p=new URLSearchParams({action:"session-objects",clientKey:clientKey(),count:String(count)});if(qs.get("review"))p.set("review","1");const res=await fetch(`/api/knowledge-vault?${p}`);const data=await res.json();const objects=data.ok?(data.objects||[]):[];setRows(objects);if(objects.length){const s=await fetch("/api/knowledge-vault",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"startSession",clientKey:clientKey(),mode:qs.get("today")?"todays5":"quick_scan",objectIds:objects.map((x:Obj)=>x.id),settings:{count}})});const sj=await s.json();if(sj.ok)setSession(sj.session);}setBusy(false);}
  useEffect(()=>{void load();},[]);
  const current=rows[index];
  async function rate(rating:string){if(!current)return;await fetch("/api/knowledge-vault",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"rate",clientKey:clientKey(),objectId:current.id,rating})});const next=index+1;if(session)await fetch("/api/knowledge-vault",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"updateSession",clientKey:clientKey(),sessionId:session.id,current_index:next,status:next>=rows.length?"completed":"active"})});if(next>=rows.length){setIndex(rows.length);setRevealed(false);}else{setIndex(next);setRevealed(false);}}
  useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key===" "){e.preventDefault();setRevealed(true);}if(revealed&&e.key==="1")void rate("Again");if(revealed&&e.key==="2")void rate("Hard");if(revealed&&e.key==="3")void rate("Got It");if(revealed&&e.key==="4")void rate("Mastered");if(e.key==="Escape")window.location.assign("/knowledge-vault");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[revealed,current,index,session,rows.length]);
  if(busy)return <div className="kv-mode-card">Building your session…</div>;if(!rows.length)return <Empty text="Quick Scan is ready, but the canonical CF3 objects are not imported yet."/>;if(index>=rows.length)return <section className="kv-mode-card kv-empty"><b>Session complete.</b><p>Your ratings have been saved to Knowledge Vault progress.</p><button onClick={()=>window.location.assign("/dashboard/knowledge-vault")}>View Knowledge Analytics →</button></section>;
  return <div className="kv-session-shell"><div className="kv-session-bar"><span>Knowledge Vault › {current.category}</span><b>{index+1} / {rows.length}</b><span>D{current.difficulty} · {current.source_kind==="source_grounded"?"Verified Source":"Capital Forge Authored"}</span></div><div className="kv-session-card"><div className="kv-object-meta"><span>{current.universe}</span><span>{current.category}</span><span>{current.content_type}</span></div><h2>{current.title}</h2><div className="kv-object-prompt"><small>{current.question_type||"Recall Prompt"}</small><p>{current.prompt||current.content?.prompt||current.content?.question||"Recall the core idea, mechanics and why it matters."}</p></div>{revealed?<LearningObjectRenderer object={current} compact/>:<button className="kv-reveal" onClick={()=>setRevealed(true)}>Reveal Answer <small>(Space)</small></button>}</div>{revealed&&<div className="kv-rating-bar"><button onClick={()=>rate("Again")}>1 · Again</button><button onClick={()=>rate("Hard")}>2 · Hard</button><button onClick={()=>rate("Got It")}>3 · Got It</button><button onClick={()=>rate("Mastered")}>4 · Mastered</button></div>}</div>;
}

function Quiz(){
  const [count,setCount]=useState(10);const [started,setStarted]=useState(false);if(started)return <QuickScan/>;return <section className="kv-mode-card"><h2>Knowledge Quiz</h2><p>Build a persisted quiz from canonical Knowledge Vault objects.</p><div className="kv-filter-row"><select value={count} onChange={e=>setCount(Number(e.target.value))}>{[5,10,20,50].map(x=><option key={x} value={x}>{x} questions</option>)}</select><select><option>All Universes</option><option>Technicals</option><option>Market History</option><option>Crises & Events</option></select><select><option>All Difficulty</option><option>Previously incorrect</option><option>Unseen</option><option>Bookmarked</option></select><button onClick={()=>{history.replaceState(null,"",`/knowledge-vault/quiz?count=${count}`);setStarted(true);}}>Start Quiz →</button></div></section>;
}

function Timeline({search}:{search:string}){const [rows,setRows]=useState<Obj[]>([]);useEffect(()=>{(async()=>{const p=new URLSearchParams({action:"timeline",limit:"50"});if(search)p.set("q",search);const res=await fetch(`/api/knowledge-vault?${p}`);const data=await res.json();if(data.ok)setRows(data.objects||[]);})();},[search]);if(!rows.length)return <Empty text="Timeline is ready for dated canonical events."/>;return <section className="kv-mode-card"><div className="kv-filter-row"><select><option>All Events</option><option>Crises</option><option>Central Banks</option><option>Corporate</option><option>Trades</option><option>M&A</option><option>IPO</option><option>Currency</option><option>Bank Failures</option></select></div>{rows.map(x=><button key={x.id} className="kv-browser-card" style={{width:"100%",marginBottom:8}} onClick={()=>window.location.assign(`/knowledge-vault/object/${x.id}`)}><small>{x.event_date} · {x.category}</small><h3>{x.title}</h3></button>)}</section>}

function Saved(){const [kind,setKind]=useState("bookmarks");const [rows,setRows]=useState<Obj[]>([]);useEffect(()=>{const qs=new URLSearchParams(window.location.search);const initial=qs.get("kind")||kind;setKind(initial);},[]);useEffect(()=>{(async()=>{const res=await fetch(`/api/knowledge-vault?action=saved&clientKey=${encodeURIComponent(clientKey())}&kind=${encodeURIComponent(kind)}`);const data=await res.json();if(data.ok)setRows(data.objects||[]);})();},[kind]);return <section className="kv-mode-card"><div className="kv-filter-row">{[["bookmarks","Bookmarks"],["incorrect","Incorrect Answers"],["review","Review Later"],["mastered","Mastered"],["recent","Recently Viewed"]].map(([k,l])=><button key={k} onClick={()=>setKind(k)}>{l}</button>)}</div>{rows.length?<div className="kv-browser-grid">{rows.map(x=><button className="kv-browser-card" key={x.id} onClick={()=>window.location.assign(`/knowledge-vault/object/${x.id}`)}><small>{x.category}</small><h3>{x.title}</h3><p>{x.progress?.status||"Saved"}</p></button>)}</div>:<Empty text="Nothing saved in this view yet."/>}</section>}

function ProgressRedirect(){useEffect(()=>{window.location.replace("/dashboard/knowledge-vault");},[]);return <div className="kv-mode-card">Opening Knowledge Vault Analytics…</div>}
